version: 2
updates:
  # NPM-Abhängigkeiten aktualisieren
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
    reviewers:
      - "saschaschneiders"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # GitHub Actions aktualisieren
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 